module.exports = {
  "LAMP RUMP (OFFER LAMP LEG) - LAMP LEG": "meat",
  "FROZEN CHICKEN LEG": "meat",
  "CALF'S LIVER - BEEF LIVER": "meat",
  "BEEF SIRLOIN CONTRAFILLET": "meat",
  "BEEF ANTRICOT": "meat",
  "FAT TAIL": "meat",
  "BEEF RUMP": "meat",
  "CHICKEN BREAST": "meat",
  "TOMATO PASTE 830 GR": "veggie",
  "JACKFRUIT": "veggie",
  "CUCUMBER": "veggie",
  "FROZEN SPINACH": "veggie",
  "KETCHUP": "store",
  "PASTA Basedow 4": "store",
  "KIWI FRUIT": "veggie",
  "GRAPES RED": "veggie",
  "GRAPES GREEN": "veggie",
  "JALAPENO PEPPER PICKLE 5 LT": "veggie",
  "WHITE CHEESE EZINE TAHSILDAROGLU 600 GR": "store",
  "RIZE TURIST BLACK TEA 1 KG": "store",
  "DOUGH THIN FOR BAKLAVA 450 GR": "store",
  "TABLE SALT": "store",
  "OLIVE OIL": "store",
  "ROASTED GROUNDNUT 120 GR - 12 PCS": "store",
  "MCVITIE'S DIGESTIVE BISCUITS - DARK CHOCOLATE 24 PCS": "store",
  "BEEF BONELESS SILVER SIDE": "meat"
}
